### ISSUE TITLE
Handle dependencies for epics

### ISSUE THREAD

**Issue by pawelrychlik** [pawelrychlik/jira-dependency-graph#2]
IDs of issues linked to a given epic are not available by simply GETting that epic via the REST API. AFAIK, first we need to run a JQL search for issues that have `epicLink = "my-epic"`, then build the graph from all the yielded issues.

**Comment by vikstrous** [comment]
Epics seem to work for me.

**Comment by whiskeysierra** [comment]
> Epics seem to work for me.

See #3
