### ISSUE TITLE
Exclude link not excluding "relates to"

### ISSUE THREAD

**Issue by cah-brandon-trebbien** [pawelrychlik/jira-dependency-graph#24]
jira-dependency-graph.py:
--exclude-link 'relates to' --exclude-link 'SAFe Parent of' --exclude-link 'SAFe Child of' --ignore-epic --show-directions outward --ignore-subtasks --dont-traverse --local $ISSUE > $ISSUE.dot

'SAFe Parent of' and 'SAFe Child of' work
'relates to' does not

![image](https://user-images.githubusercontent.com/8320312/36923541-9ea15484-1e39-11e8-897f-3e8fa619e0d6.png)

**Comment by pawelrychlik** [comment]
Uh, I could not reproduce, TBH. I did check the "relates to" link type, all fine. `strip()` doesn't seem to break anything, so I decided to merge. Thanks @thomas0306
