### ISSUE TITLE
Change readme.md readme with Atlassian Cloud auth instructions

### ISSUE THREAD

**Issue by rafaelleonardocruz** [pawelrychlik/jira-dependency-graph#40]
Working with Atlassian Cloud, We must replace password by an API token, it's not clear on readme.me. 

I can submit a PR if you agree, but basically is something like:
> ### Authentication
> Are you using Atlassian Cloud? use your API token instead of your account password, you can generate one following these steps:
> - access https://id.atlassian.com/manage-profile/security/api-tokens
> - click on "Create API token" button and save it in a safe place
> (See more details about APIs auth on [official page](https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/)

Here's the official doc.
https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/

**Comment by pawelrychlik** [comment]
@rafaelleonardocruz the requested change makes a lot of sense, so yes please, your PR is welcome 🙏
