### ISSUE TITLE
Writing to issue_graph fails due to Google Charts GET params limit

### ISSUE THREAD

**Issue by swirlsnap** [pawelrychlik/jira-dependency-graph#6]
Trying to get this set up for one of my Jira users, on Max and Linux this works great, putting it on windows was a bit more tricky but I got it working just, but when the API call to Google Charts occurs, the returned issue_graph.png is empty :-1:  Any idea what could be going on?

**Comment by swirlsnap** [comment]
Seems that this is due to the request size being too large for Google API -- How tough would it be to use the POST option instead?

**Comment by pawelrychlik** [comment]
Hi @swirlsnap, yep, it's the limitation of GET params. But it's possible to switch to POST requests in the Google Charts API => [examples](https://developers.google.com/chart/image/docs/post_requests). It seems that it should be an easy fix in the code here.

Pull requests are welcome :)

**Comment by pawelrychlik** [comment]
This is now fixed with https://github.com/pawelrychlik/jira-dependency-graph/pull/16 🎉
